### PR TITLE
Allow user installation

### PR DESCRIPTION
**Pull request by illwieckz**
Hi, I modified the extension to get icon full path at run time (no need to `gtk-update-icon-cache` anymore) so it's now possible to install the extension it in different places (in user directory for example).

So I replaced the `Makefile` by a `configure` script that generate the Makefile for user or system-wide installation.

You need to merge PR #3 before this one.

Like the other one,  I place these changes under the very permissive [ISC License](https://raw.githubusercontent.com/illwieckz/dpm-query/master/COPYING.md) so you can relicense them to the license you want for inclusion in your own project. See #2.

### CODE REVIEW

**Comment by illwieckz** [comment]
I added a `zip` target to Makefile to be able to publish the extension on http://extensions.gnome.org
The modification I did to allow relative icon paths was needed for zip installation.

Do not publish yet the extension on extension.gnome.org, It still needs a version tag.

**Comment by illwieckz** [comment]
So @JuBan1 , as someone [answered to me](https://mail.gnome.org/archives/gnome-shell-list/2016-January/msg00012.html), the version tag in metadata.json is written by http://extensions.gnome.org and incremented each time someone uploads a new version, so there is no need to handle that part at all.

The `zip` created by the current `make zip` can be uploaded on http://extensions.gnome.org .

**Comment by JuBan1** [comment]
Thanks. Could you do me a favor and try the newest version? If it works, I can upload it to extensions.gnome.org.

**Comment by illwieckz** [comment]
yes of course, badly, I'm experiencing a strange bug, after waiting a while (hours), the extension displays a wrong color. For example if I use the performance profile (displays red), then switch to the battery profile (displays green), then wait for some hours, the extension displays starts to display red some hours later), and sometime the icon just disappear (I must redo the `Alt+F2 r` sequence)… o.O

**Comment by JuBan1** [comment]
Brilliant.. the same happened to me with the old version. That is why I changed to file monitoring (= the current version) that works perfectly for me. But now that doesn't work for you ... 

I'm at a loss. As far as I can see this is magic, not programming.

**Pull request merged**
